py_test(
    name = "test_symbolic_array",
    size = "small",
    srcs = ["test_symbolic_array.py"],
    deps = [
        "//sytorch",
        "@bazel_python//:pytest_helper",
    ],
)

py_test(
    name = "test_lightning",
    size = "medium",
    srcs = ["test_lightning.py"],
    deps = [
        "//sytorch",
        "@bazel_python//:pytest_helper",
    ],
)

py_test(
    name = "test_gurobi_solver",
    size = "small",
    srcs = ["test_gurobi_solver.py"],
    deps = [
        "//sytorch",
        "@bazel_python//:pytest_helper",
    ],
)
