py_test(
    name = "test_parameter",
    size = "small",
    srcs = ["test_parameter.py"],
    deps = [
        "//sytorch",
        "@bazel_python//:pytest_helper",
    ],
)

py_test(
    name = "test_underapprox",
    size = "small",
    srcs = ["test_underapprox.py"],
    deps = [
        "//sytorch",
        "@bazel_python//:pytest_helper",
    ],
)
