py_library(
    name = "sytorch",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":pervasives",
        "//sytorch/nn",
        "//sytorch/solver",
        "//sytorch/util",
    ],
)

py_library(
    name = "pervasives",
    srcs = ["pervasives.py"],
    visibility = ["//:__subpackages__"],
)
